In [3]:
from pathlib import Path
! pip install nib
import nibabel as nib

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for nib: filename=nib-0.5.7-py3-none-any.whl size=34853 sha256=9dfaa7f0febd7a09efa931c9feb510fb8b5007ca70f1b948e5777062549a57bc
  Stored in directory: /home/tibia/.cache/pip/wheels/1c/74/ad/7732556f998eac833ce7a45d4453045eaf52fbded1d536f44a
Successfully built nib


In [4]:
from pathlib import Path

New_DIR= Path("/home/tibia/Documents/Brain_GPT_Dataset")
nii_files = list(New_DIR.glob("*.nii.gz"))

for file in nii_files:
    img = nib.load(str(file))
    data = img.get_fdata()
    shape = data.shape
    num_slices = shape[2] if len(shape) == 3 else "Non applicable"

    print(f"Fichier: {file.name}")
    print(f"  - Shape: {shape}")
    print(f"  - Nombre de coupes (axe Z): {num_slices}")
    print(f"  - Affine:\n{img.affine}")
    print("-" * 40)



Fichier: ID_4519652e_ID_9d291c8ab5.nii.gz
  - Shape: (512, 512, 24)
  - Nombre de coupes (axe Z): 24
  - Affine:
[[ -0.48828101   0.           0.         125.        ]
 [  0.          -0.45272622  -2.0200745  141.11578369]
 [  0.          -0.18291342   4.9998555   52.51448822]
 [  0.           0.           0.           1.        ]]
----------------------------------------
Fichier: ID_46a4e5b5_ID_2a037d3a2e.nii.gz
  - Shape: (512, 512, 24)
  - Nombre de coupes (axe Z): 24
  - Affine:
[[ -0.48828125   0.           0.         125.        ]
 [  0.          -0.48828125   0.          14.        ]
 [  0.           0.           5.         274.09997559]
 [  0.           0.           0.           1.        ]]
----------------------------------------
Fichier: ID_441cea72_ID_4b13324a92.nii.gz
  - Shape: (512, 512, 24)
  - Nombre de coupes (axe Z): 24
  - Affine:
[[ -0.48828101   0.           0.         125.        ]
 [  0.          -0.45272622  -2.02007289 148.85595703]
 [  0.          -0.18291342

In [ ]:
import nibabel as nib
import numpy as np
from pathlib import Path

import matplotlib.pyplot as plt

INPUT_DIR = Path("/home/tibia/Documents/Brain_GPT_Dataset")
SLICE_OUTPUT_DIR = INPUT_DIR / "slices_png"
SLICE_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Cherche tous les .nii.gz du dossier
nii_files = list(INPUT_DIR.glob("*.nii.gz"))

for file in nii_files:
    img = nib.load(str(file))
    data = img.get_fdata()  # shape (H, W, 24)
    base_name = file.stem  # sans extension

    # Vérification
    if data.ndim != 3 or data.shape[2] != 24:
        print(f" {file.name} ignoré (shape {data.shape})")
        continue

    # Sauvegarder les slices
    for i in range(24):
        slice_2d = data[:, :, i]
        # Normalisation simple [0, 255]
        slice_norm = 255 * (slice_2d - np.min(slice_2d)) / (np.ptp(slice_2d) + 1e-8)
        slice_uint8 = slice_norm.astype(np.uint8)

        # Nom du fichier
        out_path = SLICE_OUTPUT_DIR / f"{base_name}_slice{i:02d}.png"
        plt.imsave(out_path, slice_uint8, cmap="gray")

    print(f" {file.name} : 24 slices sauvegardées dans {SLICE_OUTPUT_DIR}")

✅ ID_4519652e_ID_9d291c8ab5.nii.gz : 24 slices sauvegardées dans /home/tibia/Documents/Brain_GPT_Dataset/slices_png
✅ ID_46a4e5b5_ID_2a037d3a2e.nii.gz : 24 slices sauvegardées dans /home/tibia/Documents/Brain_GPT_Dataset/slices_png
✅ ID_441cea72_ID_4b13324a92.nii.gz : 24 slices sauvegardées dans /home/tibia/Documents/Brain_GPT_Dataset/slices_png


In [11]:
SLICE_DIR= Path("/home/tibia/Documents/Brain_GPT_Dataset/slices_png")
print(len(list(SLICE_DIR.glob("*"))))
sorted_files = sorted(SLICE_DIR.glob("*.png"))

# Affichage
for f in sorted_files:
    print(f.name)

72
ID_441cea72_ID_4b13324a92.nii_slice00.png
ID_441cea72_ID_4b13324a92.nii_slice01.png
ID_441cea72_ID_4b13324a92.nii_slice02.png
ID_441cea72_ID_4b13324a92.nii_slice03.png
ID_441cea72_ID_4b13324a92.nii_slice04.png
ID_441cea72_ID_4b13324a92.nii_slice05.png
ID_441cea72_ID_4b13324a92.nii_slice06.png
ID_441cea72_ID_4b13324a92.nii_slice07.png
ID_441cea72_ID_4b13324a92.nii_slice08.png
ID_441cea72_ID_4b13324a92.nii_slice09.png
ID_441cea72_ID_4b13324a92.nii_slice10.png
ID_441cea72_ID_4b13324a92.nii_slice11.png
ID_441cea72_ID_4b13324a92.nii_slice12.png
ID_441cea72_ID_4b13324a92.nii_slice13.png
ID_441cea72_ID_4b13324a92.nii_slice14.png
ID_441cea72_ID_4b13324a92.nii_slice15.png
ID_441cea72_ID_4b13324a92.nii_slice16.png
ID_441cea72_ID_4b13324a92.nii_slice17.png
ID_441cea72_ID_4b13324a92.nii_slice18.png
ID_441cea72_ID_4b13324a92.nii_slice19.png
ID_441cea72_ID_4b13324a92.nii_slice20.png
ID_441cea72_ID_4b13324a92.nii_slice21.png
ID_441cea72_ID_4b13324a92.nii_slice22.png
ID_441cea72_ID_4b13324a92.nii_s

In [1]:
import os
import shutil

# Définir les chemins des dossiers
source_dir = "/home/tibia/Documents/LLM/BrainGPT/data"
target_dir = "/home/tibia/Documents/LLM/BrainGPT/Dataset"

# S'assurer que le dossier cible existe
os.makedirs(target_dir, exist_ok=True)

# Parcourir tous les fichiers dans le dossier source
for filename in os.listdir(source_dir):
    if filename.endswith(".png"):
        # Extraire l'ID de l'étude à partir du nom du fichier
        # Le nom est ID_XXXXXX_ID_YYYYYY...
        parts = filename.split('_')
        if len(parts) >= 2 and parts[0] == "ID":
            study_id = parts[1]
            
            # Créer le chemin du sous-dossier de l'ID
            id_dir = os.path.join(target_dir, study_id)
            os.makedirs(id_dir, exist_ok=True)
            
            # Définir les chemins complets pour le fichier source et cible
            source_path = os.path.join(source_dir, filename)
            target_path = os.path.join(id_dir, filename)
            
            # Déplacer le fichier
            shutil.move(source_path, target_path)
            print(f"Déplacé {filename} vers {id_dir}")

print("Opération terminée.")


Déplacé ID_441cea72_ID_4b13324a92.nii_slice21.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/441cea72
Déplacé ID_4519652e_ID_9d291c8ab5.nii_slice04.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/4519652e
Déplacé ID_46a4e5b5_ID_2a037d3a2e.nii_slice02.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/46a4e5b5
Déplacé ID_441cea72_ID_4b13324a92.nii_slice01.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/441cea72
Déplacé ID_46a4e5b5_ID_2a037d3a2e.nii_slice04.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/46a4e5b5
Déplacé ID_4519652e_ID_9d291c8ab5.nii_slice05.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/4519652e
Déplacé ID_46a4e5b5_ID_2a037d3a2e.nii_slice11.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/46a4e5b5
Déplacé ID_4519652e_ID_9d291c8ab5.nii_slice14.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/4519652e
Déplacé ID_4519652e_ID_9d291c8ab5.nii_slice21.png vers /home/tibia/Documents/LLM/BrainGPT/Dataset/4519652e
Déplacé ID_46a4e5b5_ID_2a037d3a2e.nii